### PR TITLE
Make pc_patch_compress return the compressed patch

### PR DESCRIPTION
**Pull request by elemoine**
When compressing a patch from `GHT` to `LAZPERF` the pc_patch_compress function currently returns the uncompressed patch. This patch fixes the problem.

This patch removes this warning:

```
pc_patch.c: In function ‘pc_patch_compress’:                                                                                                                                                                       
pc_patch.c:248:21: warning: unused variable ‘pal’ [-Wunused-variable]                                                                                                                                              
    PCPATCH_LAZPERF *pal = pc_patch_lazperf_from_uncompressed((PCPATCH_UNCOMPRESSED*)patch);                                                                                                                       
                     ^~~
```

### CODE REVIEW

**Comment by strk** [comment]
It would be great to get an automated testcase showing the need for this fix. Do you think you can craft one ?

**Comment by elemoine** [comment]
> It would be great to get an automated testcase showing the need for this fix. Do you think you can craft one ?

Yes, I'll try to come up with something.

**Comment by elemoine** [comment]
https://github.com/pgpointcloud/pointcloud/pull/130/commits/6c2df40b1be30786a04a6c98190ff1e45c97945d adds a unit test, which revealed another bug in `pc_patch_compress`.

I also added https://github.com/pgpointcloud/pointcloud/pull/130/commits/eb87b435bf8dfb3ce780a9d085d989eebf2bed02 to fix the indentation in the `cu_pc_patch.c` file. I could create a separate PR if you want. I thought that having a separate commit was good enough.

**Comment by elemoine** [comment]
@strk This fixes actual bugs, and comes with unit tests. Please consider merging :)

**Comment by strk** [comment]
I tried looking at the diff but the indent changes made my eyes bleed.
Could you avoid style changes here ?

**Comment by elemoine** [comment]
> I tried looking at the diff but the indent changes made my eyes bleed. Could you avoid style changes here ?

I created two commits for that purpose. You can just review the first commit. The second commit is style changes only.

**Comment by elemoine** [comment]
> I created two commits for that purpose. You can just review the first commit. The second commit is style changes only.

But I can remove the second commit and create a separate PR if you really prefer.

**Comment by strk** [comment]
It would be good to have an .editorconfig (editorconfig.org) file
to dictate what the expected indentation is, and then refer to
that one for changes.

I could merge the functional commit only, but I get this:

````
cu_pc_patch_lazperf.c:38:1: warning: ‘test_schema_compression_lazperf’ defined but not used [-Wunused-function]
 test_schema_compression_lazperf(void)
 ^

**Comment by elemoine** [comment]
> cu_pc_patch_lazperf.c:38:1: warning: ‘test_schema_compression_lazperf’ defined but not used

Are you sure that's related to my changes?

**Comment by elemoine** [comment]
> It would be good to have an .editorconfig (editorconfig.org) file to dictate what the expected indentation is, and then refer to that one for changes.

Yep, and the Travis process should verify that the styling is correct. It is little messy right now.

**Comment by strk** [comment]
On Fri, Feb 10, 2017 at 06:12:19AM -0800, Éric Lemoine wrote:
> > cu_pc_patch_lazperf.c:38:1: warning: ‘test_schema_compression_lazperf’ defined but not used
> 
> Are you sure that's related to my changes?

Not at all

**Comment by elemoine** [comment]
> Not at all

I think it isn't. I am happy to look into this issue when this is merged.

**Comment by strk** [comment]
Merged

**Comment by elemoine** [comment]
> cu_pc_patch_lazperf.c:38:1: warning: ‘test_schema_compression_lazperf’ defined but not used [-Wunused-function] test_schema_compression_lazperf(void)

Adressed by https://github.com/pgpointcloud/pointcloud/pull/140.

**Pull request closed without merging**
