### PR TITLE
First draft of PC_Summary(pcpatch)

### PR DESCRIPTION
**Pull request by strk**
See #47

### CODE REVIEW

**Comment by strk** [comment]
TODO: per-dimension compression (for dimensional) and stats, test and docs

**Comment by Remi-C** [comment]
This is a most useful feature.
Json would be cool because we could use postgres to parse it and get rows if necessary

**Comment by strk** [comment]
json ready for test.

I was tempted to encode dimension as hashes keyed at dimension name, to do things like:

```
select pc_summary(p)::json#>'{dims,X,size}' from mytab
```

but... could a (invalid) schema use the same name for different dimension ?

**Comment by strk** [comment]
oh, the commit also dumps manual string fiddling (death!)

**Comment by strk** [comment]
@pramsey do I need to fully detoast a pcpatch in order to get its dimensional compression info (PCBYTES) ?

**Comment by pramsey** [comment]
Like, what compression is used for each dimension? Yes, that's hiding at the front of each dimension, and they are laid down end-to-end, so you have to read the whole thing.

**Comment by strk** [comment]
uhm, that's unfortunate, for a "summary" function.
Maybe I can pull off only a slice on each dimension end?

**Comment by strk** [comment]
If everything works as expected, the function just told me that the DIMENSIONAL compression of a table resulted in all 8 dimensions using ZLIB compression for one of my cases:
```
strk=# select count(*), (json_array_elements(pc_summary(p)::json->'dims'))->>'compr' compr from (select p from pcpatch8_main limit 1) foo group by compr
;
 count | compr
-------+-------
     8 | zlib
(1 row)
```

And, for all of 101 rows:
```
strk=# select count(*), (json_array_elements(pc_summary(p)::json->'dims'))->>'compr' compr from (select p from pcpatch8_main limit 1) foo group by compr
;
 count | compr
-------+-------
     8 | zlib
(1 row)
```

**Comment by strk** [comment]
On the other hand, a PDAL imported LiDAR, with 13 dimensions:
```
rt=# select count(*), json_array_elements(((pc_summary(p)::json)->'dims'))->>'compr' comp from (select pa p from raw20h64_300 limit 1) foo group by comp;
 count |  comp   
-------+---------
     7 | rle
     4 | zlib
     2 | sigbits
(3 rows)
```

**Comment by pramsey** [comment]
OK, feeling better now

**Comment by strk** [comment]
Squash rebased and merged to master as 3fe9d4599f8fd109d6409b561cea5eac86873d34

**Pull request closed without merging**
