### PR TITLE
Add PC_Compress function

### PR DESCRIPTION
**Pull request by strk**
See #64 for rationale

### CODE REVIEW

**Comment by strk** [comment]
Example usage:

``PC_Compress(mypatch, 'dimensional','zlib,sigbits,auto,rle');``

**Comment by Remi-C** [comment]
Wouldn't it be much better that the 3d argument is an array of text.
It would save some parsing errors, and be much more usuable.

**Comment by Remi-C** [comment]
Beside, what is the behaviour when there are too few or too many compression settings?

**Comment by strk** [comment]
The reason why 3rd argument is not an array is because its semantic depends on the 2nd argument. It makes sense for it to be an array for "dimensional" compression, but not necessarely for "ght" compression, where it may be used for some other form of configuration.

It could have been a JSON, but it's so much easier to parse text that I took the easier path there.

Omitted dimension specifications default to "auto" which means let the existing heuristic decide.

**Comment by Remi-C** [comment]
Also,
is it sane to default 3d argument to '' rather than NULL?
Same for your code, you use `*compr_in == '\0'`,
wouldn't it be better to use a NULL special value?

**Comment by strk** [comment]
Accepting NULL would require us to not mark the function as STRICT. I think an empty string is ok for expressing "nothing to add" here (rather than "unknown")

**Comment by Remi-C** [comment]
No more questions ;-)

**Comment by strk** [comment]
Some interesting info extracted with the new function:
```
    compr    |  sz  |                                                  detail                                                   
-------------+------+-----------------------------------------------------------------------------------------------------------
 unc         | 8208 | 
 dim:auto    |  803 | {rle,rle,sigbits,rle,rle,rle,rle,rle,rle,rle,rle,rle,zlib}
 dim:rle     | 1591 | {rle,rle,rle,rle,rle,rle,rle,rle,rle,rle,rle,rle,rle}
 dim:sigbits |  794 | {sigbits,sigbits,sigbits,sigbits,sigbits,sigbits,sigbits,sigbits,sigbits,sigbits,sigbits,sigbits,sigbits}
 dim:zlib    |  911 | {zlib,zlib,zlib,zlib,zlib,zlib,zlib,zlib,zlib,zlib,zlib,zlib,zlib}
(5 rows)
```

That's the size of a patch with 260 points of 13 dimensions all having the same value in 12 dimensions and a growing value from 1 to 260 in one of them.

**Comment by strk** [comment]
to be noted how "SIGBITS" compresses slightly better than "RLE" in this case (all values have value 1, so they need a single bit). Not sure what happens with the last dimension, which is a double. I expected an exception (ie: cannot use RLE/SIGBIT for doubles, as per #60) but maybe something worst is happening there...

**Comment by strk** [comment]
@Remi-C are you going to send your documentation changes as pull requests to https://github.com/strk/pointcloud/tree/pc_compress ?

Meanwhile I've tested requesting sigbits/rle compression for a "double" field and while I do not get an error from pc_compress I do get different patches as a result, this has to be fixed before merging the code.

**Comment by strk** [comment]
On a closer look it's not with a "double" field that I have the problem, but rather with an int32_t that ends up being printed as a floating point number by pc_astext after compression :!

**Comment by strk** [comment]
And it's always the _first_ value in each point being slightly off. Maybe is my function being broken, needs more checks.

**Comment by Remi-C** [comment]
Isn't the Pc_astext function using the point schema from
public.pointcloud_format ?

I directly edited the mkd in browser.

Cheers

2015-04-10 18:53 GMT+02:00 Sandro Santilli <notifications@github.com>:

**Comment by strk** [comment]
@Remi-C in-browser editing should have edited a fork of yours and prompted you to send a pull request. Did it ?

**Comment by strk** [comment]
@Remi-C ok I found 
commit c9068c712705b3aa351599685d5b7155e4e45da3

It was a bit early as the code wasn't committed yet.
Also the documentation isn't correct as also GHT is allowed.

I reverted it with 3b569a59b245a919532ebf76cb472dcbfe970dee
Please see if you can turn your edits into pull requests (I guess it just takes you to edit in your fork rather than directly in the main repo).

**Comment by strk** [comment]
About pc_astext, integer fields can have a scale, in which case they become floating point numbers. It's not an error to print them with decimal digits, only.. there was no decimal digit in input, and there isnt one in output when the patch is UNCOMPRESSED. You get the decimal digits only when the patch is compressed dimensionally with SIGBITS. I'm working on a testcase to try at reproducing the problem with master.

**Comment by strk** [comment]
One patch that, when compressing dimension 4 (int32_t) with sigbits results in a different output.
Still reducing...
```
{"pcid":10,"pts":[[-0.16,0.16,-38.41,-2.51658e+06,-1.08086e+16,-2.51658e+06,-1.08086e+16],[-0.15,0.15,-35.85,-2.34881e+06,-1.00881e+16,-2.34881e+06,-1.00881e+16],[-0.14,0.14,-33.29,-2.18104e+06,-9.36749e+15,-2.18104e+06,-9.36749e+15],[-0.13,0.13,-30.73,-2.01327e+06,-8.64691e+15,-2.01327e+06,-8.64691e+15],[-0.12,0.12,-28.17,-1.84549e+06,-7.92634e+15,-1.84549e+06,-7.92634e+15],[-0.11,0.11,-25.61,-1.67772e+06,-7.20576e+15,-1.67772e+06,-7.20576e+15],[-0.1,0.1,-23.05,-1.50995e+06,-6.48518e+15,-1.50995e+06,-6.48518e+15],[-0.09,0.09,-20.49,-1.34218e+06,-5.76461e+15,-1.34218e+06,-5.76461e+15],[-0.08,0.08,-17.93,-1.17441e+06,-5.04403e+15,-1.17441e+06,-5.04403e+15],[-0.07,0.07,-15.37,-1.00663e+06,-4.32346e+15,-1.00663e+06,-4.32346e+15],[-0.06,0.06,-12.81,-838861,-3.60288e+15,-838861,-3.60288e+15],[-0.05,0.05,-10.25,-671089,-2.8823e+15,-671089,-2.8823e+15],[-0.04,0.04,-7.69,-503316,-2.16173e+15,-503316,-2.16173e+15],[-0.03,0.03,-5.13,-335544,-1.44115e+15,-335544,-1.44115e+15],[-0.02,0.02,-2.57,-167772,-7.20576e+14,-167772,-7.20576e+14],[-0.01,0.01,-0.01,-0.01,-0.01,-0.01,-0.01],[0,0,2.55,167772,7.20576e+14,167772,7.20576e+14],[0.01,-0.01,5.11,335544,1.44115e+15,335544,1.44115e+15],[0.02,-0.02,7.67,503316,2.16173e+15,503316,2.16173e+15],[0.03,-0.03,10.23,671089,2.8823e+15,671089,2.8823e+15],[0.04,-0.04,12.79,838861,3.60288e+15,838861,3.60288e+15],[0.05,-0.05,15.35,1.00663e+06,4.32346e+15,1.00663e+06,4.32346e+15],[0.06,-0.06,17.91,1.17441e+06,5.04403e+15,1.17441e+06,5.04403e+15],[0.07,-0.07,20.47,1.34218e+06,5.76461e+15,1.34218e+06,5.76461e+15],[0.08,-0.08,23.03,1.50995e+06,6.48518e+15,1.50995e+06,6.48518e+15],[0.09,-0.09,25.59,1.67772e+06,7.20576e+15,1.67772e+06,7.20576e+15],[0.1,-0.1,28.15,1.84549e+06,7.92634e+15,1.84549e+06,7.92634e+15],[0.11,-0.11,30.71,2.01327e+06,8.64691e+15,2.01327e+06,8.64691e+15],[0.12,-0.12,33.27,2.18104e+06,9.36749e+15,2.18104e+06,9.36749e+15],[0.13,-0.13,35.83,2.34881e+06,1.00881e+16,2.34881e+06,1.00881e+16],[0.14,-0.14,38.39,2.51658e+06,1.08086e+16,2.51658e+06,1.08086e+16]]}
```

**Comment by strk** [comment]
``{"pcid":10,"pts":[[-0.16,0.16,-38.41,-2.51658e+06,-1.08086e+16,-2.51658e+06,-1.08086e+16],[0,0,2.55,167772,7.20576e+14,167772,7.20576e+14]]}``

**Comment by strk** [comment]
And here's the difference (could very well be my function's problem):
``
pc_astext | {"pcid":10,"pts":[[-0.16,0.16,-38.41,-2.51658e+06,-1.08086e+16,-2.51658e+06,-1.08086e+16],[0,0,2.55,167772,7.20576e+14,167772,7.20576e+14]]}
pc_astext | {"pcid":10,"pts":[[-0.16,0.16,-38.41,-2.51658e+06,-1.08086e+16,-2.51658e+06,-1.08086e+16],[0,0,2.55,-2.51658e+06,7.20576e+14,167772,7.20576e+14]]}
``

**Comment by strk** [comment]
I can't get to test this without the PC_Compress function because that specific layout does not result in SIGBITS compressino being used. Probably because of this:
```
NOTICE:  Common value: 0, bits:0
NOTICE:  Common value: 0, bits:0
```

**Comment by strk** [comment]
I'd note that chances are no common bits found is due to change of sign, as in -1,1 sharing no bit (that'd be the purpose of zigzag encoding, which may be considered as an addition...)

**Comment by strk** [comment]
More compression issues are found with 8bits signed integers.
I guess I'll push the function first, then move on to fix bugs while adding tests (can of worms situation...)

**Comment by strk** [comment]
commit 9c1edfccdf2bdbc7b1a8e7696201514ba45fad82 landed to master, will open new issues for compression errors

**Comment by Remi-C** [comment]
@strk I put the doc in a pull request 
https://github.com/pgpointcloud/pointcloud/pull/70

**Pull request closed without merging**
