### PR TITLE
Add FreeBSD CI with cirrus

### PR DESCRIPTION
**Pull request by lbartoletti**
This allows to test on something else than gnu/linux/gcc. :kissing_heart: :smiling_imp:

### CODE REVIEW

**Comment by lbartoletti** [comment]
Results: http://cirrus-ci.com/build/5119153186013184

You only have to enable cirrus-ci for pgpointcloud account (it's free). One can also enable macos after

**Comment by pblottiere** [comment]
Nice! Can we see the results somewhere in github actions checks too?

**Comment by lbartoletti** [comment]
> Nice! Can we see the results somewhere in github actions checks too?

Yes, If it's merged :)
You can see postgis or SFCGAL_CI repo on Github : ex. https://github.com/Oslandia/SFCGAL_CI/runs/5035625243

**Comment by pblottiere** [comment]
Thanks @lbartoletti :+1:

**Pull request merged**
