### PR TITLE
Fix pc_patch_compress leak

### PR DESCRIPTION
**Pull request by achidlow**
This fixes a memory leak in pc_patch_compress. See issue #111.

### CODE REVIEW

**Comment by mbredif** [comment]
I came across this issue as well :
- `pc_patch_dimensional_free(pcdu);` is not equivalent (as one could expect) with `pc_patch_free((PCPATCH*)pcdu);` because it does not free the stats (https://github.com/pgpointcloud/pointcloud/blob/master/lib/pc_patch.c#L85-L89).

They could be made equivalent, saving a upcast-switch-downcast round-trip by putting the stats-freeing code (possibly wrapped in a function such as `pc_patch_common_free(PCPATCH*)` ) in all the `pc_patch_*_free` specialized functions.

**Comment by achidlow** [comment]
@mbredif that sounds like a better idea, that would fix any other similar leaks in one go. I'll get on it.

**Comment by achidlow** [comment]
Okay I've made the change @mbredif suggested and made a separate `pc_patch_common_free` function. This actually revealed an error in `pc_patch_dimensional_compress` where the stats member was set by `memcpy` from another `PCPATCH_DIMENSIONAL` resulting in a double-free. So I went through every case of `pcalloc(sizeof(PCPATCH*` to make sure the `stats` member was being set correctly, either to `NULL` or through `pc_stats_clone`

**Comment by strk** [comment]
Is there an existing test in the testsuite that would make the leak evident (and confirm the fix) ?

**Comment by mbredif** [comment]
I have just [stumbled](https://travis-ci.org/mbredif/pointcloud/builds/197587351) yet again on this issue while addressing #135 in [mbredif/pointcloud/pointlist_data](/mbredif/pointcloud/tree/pointlist_data).

The non-equivalence of `pc_patch_*_free(pa)` with `pc_patch_free((PCPATCH*)pa);` is so easy oversee...

I included a [quick fix](https://github.com/mbredif/pointcloud/blob/pointlist_data/lib/pc_patch_uncompressed.c#L230) but this PR would be more relevant.

**Comment by elemoine** [comment]
> The non-equivalence of pc_patch_*_free(pa) with pc_patch_free((PCPATCH*)pa); is so easy oversee...

That's right, but couldn't the rule be "never call `pc_patch_[something]_free`, and always call `pc_patch_free`"?

**Comment by elemoine** [comment]
Replaced by https://github.com/pgpointcloud/pointcloud/pull/206.

**Pull request closed without merging**
