### PR TITLE
added database initialization script to dockerfile

### PR DESCRIPTION
**Pull request by abhineetgupta**
When starting a docker container, the database will now be automatically initialized with the postgis and pointcloud extensions, similar to [postgis dockerfile](https://github.com/postgis/docker-postgis).

### CODE REVIEW

**Comment by pblottiere** [comment]
Thanks @abhineetgupta :+1:

**Comment by jruiseco** [comment]
Would it be possible to get an example docker run command?

**Comment by pblottiere** [comment]
Hi @jruiseco,

I recently added a quick tutorial on how to use the docker image in the HTML documentation: https://pgpointcloud.github.io/pointcloud/tutorials/storing.html.

**Comment by jruiseco** [comment]
You are a rock star. Thank you.

**Pull request merged**
