### PR TITLE
Fix cmake build issues

### PR DESCRIPTION
**Pull request by elemoine**
This pull request fixes https://github.com/pgpointcloud/pointcloud/issues/122. Currently the cmake-based build system doesn't handle the case where GHT and LAZPERF are installed in a specific directory (outside `/usr`).

Also, I am wondering if it makes sense to support both cmake and autotools. Wouldn't it make sense to ditch one of the two systems? If so, which one should stay?

### CODE REVIEW

**Comment by strk** [comment]
Travis is using autotools to test, so I would not ditch that one.
That said, I trust your judgment on the need for this PR, which looks fine although I hadn't tested it.

**Comment by elemoine** [comment]
> Travis is using autotools to test, so I would not ditch that one.

I am currently working on making the Travis script work with cmake instead of autotools. I am happy to submit a PR if you are (like me) interested in ditching autotools.

**Comment by strk** [comment]
I'm happy if Travis build swith both (in a matrix).
Ditching autotools is not particularely interesting for me at the moment.

**Comment by elemoine** [comment]
Ok up to you. For your information, this is a PR in our fork that removes autotools: https://github.com/LI3DS/pointcloud/pull/27. We just think that it does not make too much sense to maintain both systems, but you may have arguments…

**Comment by strk** [comment]
No specific arguments other than last I tried it failed :)
On other projects I've found that cmake builds lacked libtool scripts
to test things before installing them (which needed to be replaced
by custom things). In other cases I found myself with my OS packaged
cmake version being too old to be able to build. Finally (least important)
I know autotools better than cmake.

The above are my points, but that said I think the least used system
will automatically vanish.

**Pull request merged**
