### PR TITLE
PC_PointN : add laz support and update NEWS file

### PR DESCRIPTION
**Pull request by pblottiere**
This PR : 
- adds laz support within the PC_PointN function
- update the NEWS file by adding the PC_PointN function with its corresponding PR number

### CODE REVIEW

**Comment by elemoine** [comment]
I modified and rebased this.

* `pc_patch_lazperf_pointn` now uses `pc_patch_uncompressed_pointn` as suggested by @mbredif
* I removed the indentation changes (to be done with a separate PR)
* I also removed the change to the NEWS file (also to be done separetely)

**Comment by elemoine** [comment]
> pc_patch_lazperf_pointn now uses pc_patch_uncompressed_pointn as suggested by @mbredif

Oops, no that doesn't work. `pc_patch_uncompressed_pointn` creates a readonly point, whose data is stored into the uncompressed patch's data block. That's the reason we need to create a non-readonly point using `pc_point_make` and memcpy the data from the patch to the point.

**Comment by mbredif** [comment]
Sorry for the misguidance ;)

**Comment by elemoine** [comment]
> Sorry for the misguidance ;)

No problem at all. It was a good way to learn about the problems of that approach. I even suspect that you did it on purpose :)

This is now ready for final review.

**Comment by elemoine** [comment]
I rebased this once again. @strk can this be merged?

**Comment by pblottiere** [comment]
I rebased and added an integration test.

**Comment by pblottiere** [comment]
I think this PR is ready to be merged.

**Comment by elemoine** [comment]
I rebased this. I will merge if Travis is happy.

**Pull request merged**
