### PR TITLE
Fixes and improvements to the README file

### PR DESCRIPTION
**Pull request by elemoine**
This PR suggests a number of fixes and improvements to the documentation.

### CODE REVIEW

**Comment by pblottiere** [comment]
Thank you for your work @elemoine!

I think a good move would be to update the PDAL pipeline too. In fact, it's JSON now, not XML anymore.

**Comment by elemoine** [comment]
> I think a good move would be to update the PDAL pipeline too. In fact, it's JSON now, not XML anymore.

Ok, I will add a commit for that.

**Comment by elemoine** [comment]
New commit added. And I added another one for the Build Status icon.

The generated page can be seen here: https://github.com/elemoine/pointcloud/blob/readme/README.md.

**Comment by pblottiere** [comment]
Thank you for updating the README @elemoine! It looks good to me!

**Pull request merged**
