### PR TITLE
Schema qualify function calls

### LINKED ISSUE #197: pg_dump fails
Hi all,

Performing a backup of my postgreSQL databases (using PostgreSQL 10.3) with the pointcloud-extension enabled fails and generates the following errors:
- pg_dump: Dumping the contents of table "points" failed: PQgetResult() failed.
- pg_dump: Error message from server: ERROR:  relation "pointcloud_formats" does not exist
- LINE 1: select schema, srid from pointcloud_formats where pcid = 1
- QUERY:  select schema, srid from pointcloud_formats where pcid = 1
- pg_dump: The command was: COPY public.points (id, pt) TO stdout

Does anyone have an idea what causes the pg_dump to fail and how to solve the issue?

### PR DESCRIPTION
**Pull request by foggel**
Since Postgresql 9.6.8, pg_dump does not include any schemas in search_path, all functions must be schema qualified.
This is my attempt to schema qualify all sql functions in extension pgpointcloud and postgis_pointcloud. 
This patch also marks the extension as reloctable=false. 

The patch itself is in commit 4a7eca7.
Commit e47db2c is not needed, it updates tests to install pgpointcloud in schema pointcloudext instead of public. 

Fixes #197

### CODE REVIEW

**Comment by autra** [comment]
@pblottiere hi \o Would you have time for this by any chance?

**Comment by pblottiere** [comment]
Hi @autra! Unfortunately I really don't have time for an in-depth review for now :(.

**Comment by autra** [comment]
hi @foggel, thanks for the patch. I tested it today. Table restoration works fine, but if there is an index on the table, it fails to restore.

The table is defined as such:

```
=# \d public.sonde
                              Table "public.sonde"
 Column │    Type    │ Collation │ Nullable │              Default
════════╪════════════╪═══════════╪══════════╪════════════════════════════════════
 id     │ integer    │           │ not null │ nextval('sondes_id_seq'::regclass)
 patch  │ pcpatch(1) │           │          │
Indexes:
    "sondes_pkey" PRIMARY KEY, btree (id)
    "sonde_patch_idx" gist ((patch::geometry))
```

And the restore command yields the following error:

```sql
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 5618; 1259 5545561 INDEX sonde_patch_idx postgres
pg_restore: error: could not execute query: ERROR:  function pc_envelopeasbinary(public.pcpatch) does not exist
LINE 2:   SELECT ST_GeomFromEWKB(PC_EnvelopeAsBinary($1))
                                 ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:
                SELECT ST_GeomFromEWKB(PC_EnvelopeAsBinary($1))

CONTEXT:  SQL function "pc_envelopegeometry" during inlining
Command was: CREATE INDEX sonde_patch_idx ON public.sonde USING gist (((patch)::public.geometry));


pg_restore: warning: errors ignored on restore: 1
```

**Comment by foggel** [comment]
Looks like I forgot to commit the changes for pointcloud_postgis (pointcloud_postgis-1.2.1.sql). I will try to commit before the weekend, unfortunately I have deleted my local copy.

**Comment by foggel** [comment]
I can't reproduce that error. Can you try reinstall pointcloud_postgis extension?

**Comment by autra** [comment]
> I can't reproduce that error. Can you try reinstall pointcloud_postgis extension?

I have reinstalled everything and me neither :-D So I must have messed up an installation somewhere. Sorry for the noise!

**Comment by pblottiere** [comment]
Thanks a lot for this PR @foggel :+1:!

Superseded by https://github.com/pgpointcloud/pointcloud/pull/301.

**Pull request closed without merging**
